### ISSUE TITLE
Use navbar html that's local

### ISSUE THREAD

**Issue by penelopeysm** [TuringLang/actions#2]
We should probably use the navbar html that's in the action repository:

```yaml
  navbar-url:
    description: 'URL of the navbar HTML to be inserted.'
    required: false
    default: ${{ github.action_path }}/scripts/TuringNavbar.html
```

The insert_navbar.sh script will have to be modified for this though because it uses `curl` right now (whereas if it's local we probably just want to use `cat`).
