### ISSUE TITLE
Add comment preview URL functionality to Docs action

### ISSUE THREAD

**Issue by penelopeysm** [TuringLang/actions#8]
We have this on the `docs` repo, but none of the other ones

```yaml
      - name: Comment preview URL
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            <!-- preview-url-comment -->
            Preview the changes: https://turinglang.org/docs/pr-previews/${{ github.event.pull_request.number }}
            Please avoid using the search feature and navigation bar in PR previews!
          comment_tag: preview-url-comment
```
